/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <string.h>
#include <time.h>

void
add_prog_1(char *host,int a,int b)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a=a;
	add_1_arg.b=b;
	add_1(&add_1_arg, clnt);
	//if (result_1 == (int *) NULL) {
	//	clnt_perror (clnt, "call failed");
	//}else{
	//	printf("The result is: %d\n",*result_1);
	//}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clock_t before = clock(); 
	for(int iterator=0;iterator<1000;iterator++){
		add_prog_1 (host,atoi(argv[2])+iterator,iterator);
		printf("Hi! This is client calling server %d\n",iterator);
	}
	
	clock_t after = clock();
	
	/*int sockfd, portno, n;
	struct sockaddr_in serv_addr;
	struct hostent *server;
	char buffer[1024];
	
	
	portno = atoi(argv[4]); // Port number in integer
	sockfd = socket(AF_INET, SOCK_STREAM, 0);
	if (sockfd < 0)
		error("ERROR opening socket");
	server = gethostbyname(argv[1]); // Host name to IP number
	if (server == NULL)
		error("ERROR, no such host\n");
	bzero((char *) &serv_addr, sizeof(serv_addr));
	serv_addr.sin_family = AF_INET;
	
	
	bcopy((char *)server->h_addr, (char *)&serv_addr.sin_addr.s_addr, server->h_length);
	serv_addr.sin_port = htons(portno);
	if (connect(sockfd,(struct sockaddr *)&serv_addr,sizeof(serv_addr))< 0)
		error("ERROR in connecting");
	printf("Please enter the message: "); // Input prompt for client msg.
	
	bzero(buffer,1024);
	fgets(buffer,1024,stdin); // Get the msg from stdin
	n = write(sockfd,buffer,strlen(buffer));
	if (n < 0)
		error("ERROR writing to socket");
	bzero(buffer,1024);
	n = read(sockfd,buffer,1024);
	if (n < 0)
		error("ERROR reading from socket");
	printf("Server replies: %s\n",buffer);
	close(sockfd);*/
	
	printf("%ld\n",(after - before)/1000000);

	exit (0);
}
