/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "add.h"

/* Default timeout can be changed using clnt_control() */

static struct timeval TIMEOUT = { 0, 0 };

void
add_1(numbers *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, add,
		(xdrproc_t) xdr_numbers, (caddr_t) argp,
		NULL, NULL,
		TIMEOUT) != RPC_SUCCESS) {
		//return (NULL);
	}


}
