/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include<stdio.h>
#include<stdlib.h>
#include<sys/types.h>
#include<sys/socket.h>
#include<netinet/in.h>
#include<string.h>

//error handling
void error(char *msg){
	perror(msg);
	exit(1);
}


int *add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
	sleep(2);

	printf("Testing server running(asynchronous....) which is called from function %d\n",argp->b);
	result = argp->a*argp->b;

	

	return &result;
}
