/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASYNCRPC_H_RPCGEN
#define _ASYNCRPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct authenticateDatatype {
	int userId;
	int password;
	int portNo;
};
typedef struct authenticateDatatype authenticateDatatype;

struct showAllBooksDatatype {
	int portNo;
};
typedef struct showAllBooksDatatype showAllBooksDatatype;

struct isuueBookDatatype {
	int userId;
	int bookId;
	int portNo;
};
typedef struct isuueBookDatatype isuueBookDatatype;

struct returnBookDatatype {
	int userId;
	int bookId;
	int portNo;
};
typedef struct returnBookDatatype returnBookDatatype;

#define ASYNCHRONOUSRPC_PROG 0x56843572
#define ASYNCHRONOUSRPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define authenticate 1
extern  void * authenticate_1(authenticateDatatype *, CLIENT *);
extern  void * authenticate_1_svc(authenticateDatatype *, struct svc_req *);
#define showAllBooks 2
extern  void * showallbooks_1(showAllBooksDatatype *, CLIENT *);
extern  void * showallbooks_1_svc(showAllBooksDatatype *, struct svc_req *);
#define isuueBook 3
extern  void * isuuebook_1(isuueBookDatatype *, CLIENT *);
extern  void * isuuebook_1_svc(isuueBookDatatype *, struct svc_req *);
#define returnBook 4
extern  void * returnbook_1(returnBookDatatype *, CLIENT *);
extern  void * returnbook_1_svc(returnBookDatatype *, struct svc_req *);
extern int asynchronousrpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define authenticate 1
extern  void * authenticate_1();
extern  void * authenticate_1_svc();
#define showAllBooks 2
extern  void * showallbooks_1();
extern  void * showallbooks_1_svc();
#define isuueBook 3
extern  void * isuuebook_1();
extern  void * isuuebook_1_svc();
#define returnBook 4
extern  void * returnbook_1();
extern  void * returnbook_1_svc();
extern int asynchronousrpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_authenticateDatatype (XDR *, authenticateDatatype*);
extern  bool_t xdr_showAllBooksDatatype (XDR *, showAllBooksDatatype*);
extern  bool_t xdr_isuueBookDatatype (XDR *, isuueBookDatatype*);
extern  bool_t xdr_returnBookDatatype (XDR *, returnBookDatatype*);

#else /* K&R C */
extern bool_t xdr_authenticateDatatype ();
extern bool_t xdr_showAllBooksDatatype ();
extern bool_t xdr_isuueBookDatatype ();
extern bool_t xdr_returnBookDatatype ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASYNCRPC_H_RPCGEN */
