/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "asyncRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 0, 0 };

void *
authenticate_1(authenticateDatatype *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, authenticate,
		(xdrproc_t) xdr_authenticateDatatype, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		//return (NULL);
	}
	//return ((void *)&clnt_res);
}

void *
showallbooks_1(showAllBooksDatatype *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, showAllBooks,
		(xdrproc_t) xdr_showAllBooksDatatype, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		//return (NULL);
	}
	//return ((void *)&clnt_res);
}

void *
isuuebook_1(isuueBookDatatype *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, isuueBook,
		(xdrproc_t) xdr_isuueBookDatatype, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		//return (NULL);
	}
	//return ((void *)&clnt_res);
}

void *
returnbook_1(returnBookDatatype *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, returnBook,
		(xdrproc_t) xdr_returnBookDatatype, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		//return (NULL);
	}
	//return ((void *)&clnt_res);
}
