/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "asyncRPC.h"

bool_t
xdr_authenticateDatatype (XDR *xdrs, authenticateDatatype *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->userId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->password))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->portNo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_showAllBooksDatatype (XDR *xdrs, showAllBooksDatatype *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->portNo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_isuueBookDatatype (XDR *xdrs, isuueBookDatatype *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->userId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bookId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->portNo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnBookDatatype (XDR *xdrs, returnBookDatatype *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->userId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bookId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->portNo))
		 return FALSE;
	return TRUE;
}
